Settings/Contact Us
SoftTeco/AndroidAppTemplate pull request #112
Opened 2023-11-23 11:54 UTC by anastasiaShpakava

## Summary

Added Contac Us to Settings toolbar

## Reasons
User will  be able to contact the app support team conveniently from the mobile app settings. This will allow user to easily reach out to the support team for any questions, feedback, or issues related to the app.

## References

closes https://github.com/SoftTeco/AndroidAppTemplate/pull/97

2023-11-23 22:20 UTC, bstolyarov requested changes

2023-11-23 22:20 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/ui/feature/settings/SettingsScreen.kt
> +                    context.sendMail(recipient = "softteco.os.dev@gmail.com", subject = "User Inquiry or Feedback")
Let's move "softteco.os.dev@gmail.com" and "User Inquiry or Feedback" to constants.

2023-11-23 22:20 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/ui/feature/settings/SettingsScreen.kt
> +                        contentDescription = "Settings description"
We translated a contentDescription in this app before. Let's use string res for this as well. Also, it should be different names for contentDescription for different list items.

2023-11-23 22:20 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/ui/feature/settings/SettingsScreen.kt
> +            ListItem(
Could you make a common list item component for this list

2023-11-23 22:20 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/utils/SendEmailExtension.kt
Let's name this file `ContextExtension`

2023-11-28 09:29 UTC, bstolyarov approved these changes

2023-11-28 10:09 UTC, EvgeniyFilippov approved these changes

2023-11-28 10:14 UTC, merged