Add Firebase push notifications
SoftTeco/AndroidAppTemplate pull request #121
Opened 2023-12-04 15:40 UTC by anastasiaShpakava

## Summary

Added Firebase push notifications 

## Reasons

User will  be able to get push notifications from the Firebase console.

## References

closes https://github.com/SoftTeco/AndroidAppTemplate/issues/102

2023-12-05 22:56 UTC, EvgeniyFilippov commented on app/src/main/kotlin/com/softteco/template/ui/AppContent.kt
> +            Log.d("FCM token:", token)
it is better to use Timber instead of Log

2023-12-05 23:02 UTC, EvgeniyFilippov commented on app/build.gradle.kts
> +    id("com.google.gms.google-services") version "4.3.15"
the latest version is 4.4.0

2023-12-05 23:19 UTC, EvgeniyFilippov approved these changes

2023-12-06 08:38 UTC, bstolyarov requested changes

2023-12-06 08:38 UTC, bstolyarov commented on app/google-services.json
> +{
Could we hide this file?

2023-12-06 16:15 UTC, bstolyarov requested changes

2023-12-12 10:21 UTC, merged