Add firebase analytics
SoftTeco/AndroidAppTemplate pull request #144
Opened 2024-01-25 10:59 UTC by EvgeniyFilippov

## Summary

Added firebase analytics and base events

## Reasons

Base analytics implementation

## References
closes #143

2024-01-25 12:44 UTC, anastasiaShpakava approved these changes

2024-01-26 07:02 UTC, bstolyarov commented
It's already better, but what I expect to see: 
1. Main Analytic class `Analytic` is a singleton, we can use it in the way `Analytic.homeOpened()`. 
2. Inside, `Analytic` contains a provider `var provider: AnalyticsProvider? = null`, only the provider knows about the event tracking library. 
3. AnalyticsProvider is an interface, we can provide any implementation via DI. 
4. `Analytic.homeOpened()` function calls provider for tracking analytics `fun homeOpened() = provider?.logEvent(Event.HOME_OPENED)
5. As you can see events string located in Constants
6. How do we set the provider to Analytic Singleton? For that, we make a function in `Analytic` like: 
```
    private var provider: AnalyticsProvider? = null
    fun init(provider: AnalyticsProvider) {
        this.provider = provider
    }
```
And init it in the Application class in onCreate.
7. For Firebase, we make FirebaseAnalyticProvider, and provide it in DI for AnalyticsProvider interface.

2024-01-26 07:03 UTC, bstolyarov requested changes
Left a separate comment

2024-02-05 20:05 UTC, bstolyarov approved these changes
Nice 👍

2024-02-06 15:21 UTC, merged