Fix navigation after login
SoftTeco/AndroidAppTemplate pull request #153
Opened 2024-02-09 14:18 UTC by anastasiaShpakava

## Summary
Add `BackuttonHandler` for handling click of system back button.

## Reasons
Closing the app when the system back button is pressed can help users quickly exit the app and return to the device's home screen or previous task. It's also a common design pattern to prevent users from getting stuck in a loop of navigating back through screens indefinitely.

## References
closes #151 .

2024-02-10 09:57 UTC, EvgeniyFilippov approved these changes

2024-02-13 10:49 UTC, bstolyarov requested changes
Has a wrong behavior

2024-02-16 13:39 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/MainActivity.kt
> +                    AppContent(startDestination, { isUserLoggedIn = it })
Why changing `isUserLoggedIn` via callback works better then 
`isUserLoggedIn = profileRepository.getUser() is Result.Success`?
It seems they should work similarly.

2024-02-16 14:13 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/MainActivity.kt
> +                    AppContent(startDestination, { isUserLoggedIn = it })
It's a good catch! 
Could we add some SessionManager to handle if a user logged in? The SessionManager could be a singleton, injected to MainActivity and in places where we do login\logout. In MainActivity we will just collect a state field of SessionManager. 
So in this way, we will avoid adding the callback for handling whether the user logged in or logged out

2024-02-26 12:58 UTC, bstolyarov approved these changes

2024-02-26 13:52 UTC, EvgeniyFilippov approved these changes

2024-02-26 14:11 UTC, merged