Feature/login screen
SoftTeco/AndroidAppTemplate pull request #24
Opened 2023-09-08 14:35 UTC by anastasiaShpakava

2023-09-11 08:23 UTC, pcfaktor requested changes

2023-09-11 22:05 UTC, bstolyarov requested changes

2023-09-11 22:05 UTC, bstolyarov commented on gradle/libs.versions.toml
> +androidx-compose-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "composeDesugar" }
Why do we need it?

2023-09-11 22:05 UTC, bstolyarov commented on app/src/main/res/values/strings.xml
> +    <string name="birth_day">Birth day</string>
It's probably unused

2023-09-12 07:00 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/data/profile/dto/CreateUserDto.kt
> +    @field:Json(name = "firstName") val firstName: String,
I'm not sure if this has had time to become standard.) Anyway, it is out of the scope of PR

2023-09-12 07:07 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/data/profile/dto/LoginAuthDto.kt
> +data class LoginAuthDto(
It is good practice to label fields with their original names. We have no control over the names on the backend side. Sometimes they don't conform to our naming convention or they don't fit for some other reason. There is also the possibility that someone could rename a field (DTO), which could cause problems.

2023-09-12 07:19 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/login/LoginScreen.kt
> +	TextSnackbarContainer(
The component was intended that way. It encapsulates inside itself the box with all screen contents and a SnackbarHost above it

2023-09-12 07:20 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/ValidateFields.kt
> +	fun String.isFieldEmpty(): Boolean {
Discussed in the background

2023-09-12 07:22 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/feature/signUp/SignUpViewModel.kt
> +			val loading = array[0] as Boolean
Discussed in the background. Utils ```combine``` fun for more parameters will be implemented.

2023-09-12 07:23 UTC, pcfaktor commented on app/src/main/kotlin/com/softteco/template/ui/theme/Dimens.kt
> +    val PaddingMiddle: Dp = 40.dp
Discussed in the background

2023-09-12 09:38 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/data/profile/dto/CreateUserDto.kt
> +    @field:Json(name = "firstName") val firstName: String,
It's not a standard for development, I mean it's from JetBrains so it's something natural, default I would say. 
Agree that it's out of scope, let's discuss it separately.

2023-09-12 09:41 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/data/profile/dto/LoginAuthDto.kt
> +data class LoginAuthDto(
If the backend has a different field name we can add annotation for this single field. 
The same as if a backend changes a field name, we also can add an annotation for the updated field, without changing dto field. 
In cases when 99% of fields are equal, annotations look boilerplate. 
Can discuss it in the background :)

2023-09-12 15:22 UTC, pcfaktor approved these changes
Good job!

2023-09-13 07:09 UTC, bstolyarov commented on app/src/main/kotlin/com/softteco/template/ui/feature/login/LoginViewModel.kt
> +	private fun handleError(error: ErrorEntity) {
Let's do it in separate PR

2023-09-13 07:11 UTC, bstolyarov approved these changes
@anastasiaShpakava Great job! 
@pcfaktor Thank you!

2023-09-13 07:15 UTC, merged